src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     * @Assert\Length(
     *      min = 6,
     *      max = 100,
     *      minMessage = "Пароль должен содержать не меньше {{ limit }} символов",
     *      maxMessage = "Пароль должен содержать не меньше {{ limit }} символов"
     * )
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $fullName;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isBlocked;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photo;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateOfBirth;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $phone;

    /**
     * @ORM\ManyToOne(targetEntity=Sex::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $sex;

    /**
     * @ORM\OneToMany(targetEntity=Subscription::class, mappedBy="subscribedUser", orphanRemoval=true)
     */
    private $subscriptions;

    public function __construct()
    {
        $this->subscriptions = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFullName(): ?string
    {
        return $this->fullName;
    }

    public function setFullName(string $fullName): self
    {
        $this->fullName = $fullName;

        return $this;
    }

    public function getIsVerified(): ?bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getIsBlocked(): ?bool
    {
        return $this->isBlocked;
    }

    public function setIsBlocked(bool $isBlocked): self
    {
        $this->isBlocked = $isBlocked;

        return $this;
    }

    public function getIsAdmin(): bool
    {
        return in_array('ROLE_ADMIN', $this->getRoles());
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getDateOfBirth(): ?\DateTimeInterface
    {
        return $this->dateOfBirth;
    }

    public function setDateOfBirth(\DateTimeInterface $dateOfBirth): self
    {
        $this->dateOfBirth = $dateOfBirth;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getSex(): ?Sex
    {
        return $this->sex;
    }

    public function setSex(Sex $sex): self
    {
        $this->sex = $sex;

        return $this;
    }

    public function __toString(): string
    {
        return (string)$this->getFullName();
    }

    /**
     * @return Collection|Subscription[]
     */
    public function getSubscriptions(): Collection
    {
        return $this->subscriptions;
    }

    public function addSubscription(Subscription $subscription): self
    {
        if (!$this->subscriptions->contains($subscription)) {
            $this->subscriptions[] = $subscription;
            $subscription->setSubscribedUser($this);
        }

        return $this;
    }

    public function removeSubscription(Subscription $subscription): self
    {
        if ($this->subscriptions->removeElement($subscription)) {
            // set the owning side to null (unless already changed)
            if ($subscription->getSubscribedUser() === $this) {
                $subscription->setSubscribedUser(null);
            }
        }

        return $this;
    }
}

src/Controller/FitnessClubController.php
<?php

namespace App\Controller;

use App\Entity\GroupFitnessClasses;
use App\Entity\NotificationMessage;
use App\Entity\Subscription;
use App\Entity\User;
use App\Form\SubscriptionType;
use App\Form\UserNotificationType;
use App\Message\NotificationEmail;
use App\Message\NotificationSms;
use App\Repository\GroupFitnessClassesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Messenger\Bridge\Amqp\Transport\AmqpSender;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Component\Notifier\Notification\Notification;
use Symfony\Component\Notifier\NotifierInterface;
use Symfony\Component\Routing\Annotation\Route;

class FitnessClubController extends AbstractController
{
    /**
     * @Route("/", name="class_list")
     */
    public function index(GroupFitnessClassesRepository $groupFitnessClassesRepository): Response
    {
        return $this->render('fitness_club/index.html.twig', [
            'group_fitness_classes' => $groupFitnessClassesRepository->findAll()
        ]);
    }

    /**
     * @Route("/class/{id}", name="class_detail")
     */
    public function detail(GroupFitnessClasses $groupFitnessClass): Response
    {
        return $this->render('fitness_club/detail.html.twig', [
            'group_fitness_class' => $groupFitnessClass
        ]);
    }

    // Вынес формы т.к. экшн детальной получился довольно "толстым"
    public function subscriptionForm(Request $request, GroupFitnessClasses $groupFitnessClass,
                                     NotifierInterface $notifier): Response
    {
        /** @var User|null $user */
        $user = $this->getUser();
        if (!$user) {
            return new Response();
        }

        $entityManager = $this->getDoctrine()->getManager();
        $subscription = $entityManager->getRepository(Subscription::class)
            ->findOneBy([
                'subscribedUser' => $user,
                'groupFitnessClass' => $groupFitnessClass
            ]);

        if (empty($subscription)) {
            $subscription = new Subscription();
            $subscription->setSubscribedUser($user);
            $subscription->setGroupFitnessClass($groupFitnessClass);
        }

        $subscriptionForm = $this->createForm(SubscriptionType::class, $subscription);
        $subscriptionForm->handleRequest($request);

        if ($subscriptionForm->isSubmitted() && $subscriptionForm->isValid()) {
            // если есть id значит способ связи существует в базе и это подписка
            if ($subscription->getContactType()->getId()) {
                $entityManager->persist($subscription);
                $entityManager->flush();

                $notifier->send(new Notification('Подписка оформлена!', ['browser']));
            } else {
                // в противном случае это отписка
                $entityManager->remove($subscription);
                $entityManager->flush();

                $notifier->send(new Notification('Подписка отменена!', ['browser']));
            }
        }

        return $this->render('fitness_club/forms/subscription.html.twig', [
            'subscription_form' => $subscriptionForm->createView()
        ]);
    }

    public function userNotificationForm(Request $request, GroupFitnessClasses $groupFitnessClass,
                                         MessageBusInterface $bus, NotifierInterface $notifier): Response
    {
        /** @var User|null $user */
        $user = $this->getUser();
        if (!$user || !$user->getIsAdmin()) {
            return new Response();
        }

        $notificationMessage = new NotificationMessage();
        $userNotificationForm = $this->createForm(UserNotificationType::class, $notificationMessage);
        $userNotificationForm->handleRequest($request);

        if ($userNotificationForm->isSubmitted() && $userNotificationForm->isValid()) {
            if ($notificationMessage->getEmailMessage()) {
                foreach ($groupFitnessClass->getEmailSubscriptions() as $subscription) {
                    $bus->dispatch(new NotificationEmail($subscription, $notificationMessage->getEmailMessage()));
                }

                $notifier->send(new Notification('Email отправлены!', ['browser']));
            }

            if ($notificationMessage->getSmsMessage()) {
                foreach ($groupFitnessClass->getSmsSubscriptions() as $subscription) {
                    $bus->dispatch(new NotificationSms($subscription, $notificationMessage->getSmsMessage()));
                }

                $notifier->send(new Notification('Sms отправлены!', ['browser']));
            }
        }

        return $this->render('fitness_club/forms/user-notification.html.twig', [
            'user_notification_form' => $userNotificationForm->createView()
        ]);
    }
}

templates/fitness_club/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ group_fitness_class.name }} {% endblock %}

{% block body %}
    <div class="row">
        <div class="col-sm-8">
            <h1>{{ group_fitness_class.name }}</h1>
            <p><b>Тренер: {{ group_fitness_class.couchName }}</b></p>
            <p>{{ group_fitness_class.description|raw }}</p>
        </div>

            <div class="col-sm-4">
                {{ render(controller(
                    'App\\Controller\\FitnessClubController::subscriptionForm',
                    {
                        request: app.request,
                        user: app.user,
                        groupFitnessClass: group_fitness_class
                    }
                )) }}
                {{ render(controller(
                    'App\\Controller\\FitnessClubController::userNotificationForm',
                    {
                        request: app.request,
                        user: app.user,
                        groupFitnessClass: group_fitness_class
                    }
                )) }}
            </div>
    </div>
{% endblock %}

templates/fitness_club/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} Список групповых занятий {% endblock %}

{% block body %}
    <div class="row">
        {% for group_fitness_class in group_fitness_classes %}
            <div class="col-sm-6">
                <a href="{{ path('class_detail', {id: group_fitness_class.id}) }}" class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ group_fitness_class.name }}</h5>
                        <p class="card-text">{{ group_fitness_class.couchName }}</p>
                        {% if app.user %}
                            {% for subscription in app.user.subscriptions %}
                                {% if subscription.groupFitnessClass.id == group_fitness_class.id %}
                                    <div class="alert alert-success">
                                        <p class="card-text">
                                            Оформлена подписка: {{ subscription.contactType }}
                                        </p>
                                    </div>
                                {% endif %}
                            {% endfor %}

                            {% if app.user.isAdmin %}
                                <div class="alert alert-info">
                                    <p class="card-text">
                                        Количество подписчиков: {{ group_fitness_class.subscriptions.count() }}
                                    </p>
                                </div>
                            {% endif %}
                        {% endif %}
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}